package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_profile_redirect_dashboard",
    actual = "//tensorboard/plugins/profile_redirect/polymer3/tf_profile_redirect_dashboard:tf_profile_redirect_dashboard",
)
