load("//tensorboard/defs:web.bzl", "tf_web_library")

package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])

tf_web_library(
    name = "roboto",
    srcs = [
        "roboto.html",
    ],
    path = "/tf-imports",
    deps = [
        "@com_google_fonts_roboto",
    ],
)
