package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_hparams_main",
    actual = "//tensorboard/plugins/hparams/polymer3/tf_hparams_main:tf_hparams_main",
)
