package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tensor_widget",
    actual = "//tensorboard/components_polymer3/tensor_widget:tensor_widget",
)

alias(
    name = "tensor_widget_binary",
    actual = "//tensorboard/components_polymer3/tensor_widget:tensor_widget_binary",
)

alias(
    name = "tensor_widget_binary_lib",
    actual = "//tensorboard/components_polymer3/tensor_widget:tensor_widget_binary_lib",
)

alias(
    name = "tensor_widget_lib",
    actual = "//tensorboard/components_polymer3/tensor_widget:tensor_widget_lib",
)
