package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_custom_scalar_dashboard",
    actual = "//tensorboard/plugins/custom_scalar/polymer3/tf_custom_scalar_dashboard:tf_custom_scalar_dashboard",
)
