package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_mesh_dashboard",
    actual = "//tensorboard/plugins/mesh/polymer3/tf_mesh_dashboard:tf_mesh_dashboard",
)
