load("@io_bazel_rules_sass//:defs.bzl", "npm_sass_library")

package(default_visibility = ["//tensorboard:internal"])

npm_sass_library(
    name = "material_sass",
    deps = ["@npm//@angular/material"],
)
