package(default_visibility = ["//tensorboard:internal"])
 
licenses(["notice"])  # Apache 2.0

py_library(
    name = "witwidget",
    srcs = glob([
        "__init__.py",
        "notebook/**/*.py",
    ]),
    srcs_version = "PY2AND3",
)

py_library(
    name = "version",
    srcs = ["version.py"],
    srcs_version = "PY2AND3",
)
