load("//tensorboard/defs:defs.bzl", "tf_ts_library")

package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

tf_ts_library(
    name = "vz_sorting",
    srcs = [
        "sorting.ts",
    ],
    strict_checks = False,
)
