# Description:
# An example plugin.
load("@rules_python//python:py_library.bzl", "py_library")

package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])

py_library(
    name = "plugin",
    srcs = ["plugin.py"],
    srcs_version = "PY3",
    visibility = ["//visibility:public"],
)
