package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "standalone_lib",
    actual = "//tensorboard/plugins/projector/polymer3/vz_projector:standalone_lib",
)

alias(
    name = "vz_projector",
    actual = "//tensorboard/plugins/projector/polymer3/vz_projector:vz_projector",
)

alias(
    name = "heap",
    actual = "//tensorboard/plugins/projector/polymer3/vz_projector:heap",
)

alias(
    name = "bh_tsne",
    actual = "//tensorboard/plugins/projector/polymer3/vz_projector:bh_tsne",
)

alias(
    name = "sptree",
    actual = "//tensorboard/plugins/projector/polymer3/vz_projector:sptree",
)
