package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_tensorboard",
    actual = "//tensorboard/components_polymer3/tf_tensorboard:tf_tensorboard",
)

alias(
    name = "registry",
    actual = "//tensorboard/components_polymer3/tf_tensorboard:registry",
)

alias(
    name = "plugin_dialog",
    actual = "//tensorboard/components_polymer3/tf_tensorboard:plugin_dialog",
)

alias(
    name = "default_plugins",
    actual = "//tensorboard/components_polymer3/tf_tensorboard:default_plugins",
)
