package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_image_dashboard",
    actual = "//tensorboard/plugins/image/polymer3/tf_image_dashboard:tf_image_dashboard",
)
