package(default_visibility = ["//tensorboard:internal"])

load("//tensorboard/defs:web.bzl", "tf_web_library")

licenses(["notice"])  # Apache 2.0

tf_web_library(
    name = "utils",
    srcs = [
        "utils.html",
        "utils.ts",
    ],
    path = "/memory-viewer",
)

