package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_paginated_view",
    actual = "//tensorboard/components_polymer3/tf_paginated_view:tf_paginated_view",
)
