licenses(["notice"])  # Apache 2.0

py_binary(
    name = "import_google_fonts",
    srcs = ["import_google_fonts.py"],
    deps = ["//tensorboard:expect_tensorflow_installed"],
)

py_binary(
    name = "replace_handlebar_with_filecontent",
    srcs = ["replace_handlebar_with_filecontent.py"],
    visibility = ["//tensorboard:internal"],
)
