package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "demo",
    actual = "//tensorboard/plugins/histogram/polymer3/vz_histogram_timeseries:demo",
)

alias(
    name = "vz_histogram_timeseries",
    actual = "//tensorboard/plugins/histogram/polymer3/vz_histogram_timeseries:vz_histogram_timeseries",
)
