package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_graph_debugger_data_card",
    actual = "//tensorboard/plugins/graph/polymer3/tf_graph_debugger_data_card:tf_graph_debugger_data_card",
)
