package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_histogram_dashboard",
    actual = "//tensorboard/plugins/histogram/polymer3/tf_histogram_dashboard:tf_histogram_dashboard",
)
