package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_card_heading",
    actual = "//tensorboard/components_polymer3/tf_card_heading:tf_card_heading",
)
