package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_hparams_backend",
    actual = "//tensorboard/plugins/hparams/polymer3/tf_hparams_backend:tf_hparams_backend",
)
