package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_hparams_session_group_values",
    actual = "//tensorboard/plugins/hparams/polymer3/tf_hparams_session_group_values:tf_hparams_session_group_values",
)
