package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "vz_sorting",
    actual = "//tensorboard/components_polymer3/vz_sorting:vz_sorting",
)
