package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "vz_chart_helpers",
    actual = "//tensorboard/components_polymer3/vz_chart_helpers:vz_chart_helpers",
)
