load("//tensorboard/defs:web.bzl", "tf_web_library")

package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

tf_web_library(
    name = "tf_utils",
    srcs = [
        "tf-utils.html",
        "utils.ts",
    ],
    path = "/tf-utils",
)
