load("//tensorboard/defs:defs.bzl", "tf_ts_library")

package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])

# This is a dummy rule used as a @angular/common/http dependency.
# This is not a replacement for @angular/common dependency.
tf_ts_library(
    name = "expect_angular_common_http",
    srcs = [],
    visibility = [
        "//tensorboard/webapp/feature_flag:__subpackages__",
        "//tensorboard/webapp/webapp_data_source:__subpackages__",
    ],
    deps = [
        "@npm//@angular/common",
    ],
)

# This is a dummy rule used as a @angular/common/testing dependency.
# This is not a replacement for @angular/common dependency.
tf_ts_library(
    name = "expect_angular_common_http_testing",
    srcs = [],
    visibility = [
        "//tensorboard/webapp/feature_flag:__subpackages__",
        "//tensorboard/webapp/webapp_data_source:__subpackages__",
    ],
    deps = [
        "@npm//@angular/common",
    ],
)

# This is a dummy rule used as a @angular/material/cdk_clipboard dependency.
tf_ts_library(
    name = "expect_angular_cdk_clipboard",
    srcs = [],
    deps = [
        "@npm//@angular/cdk",
    ],
)

# This is a dummy rule used as a @angular/cdk/testing dependency.
tf_ts_library(
    name = "expect_angular_cdk_testing",
    srcs = [],
    deps = [
        "@npm//@angular/cdk",
    ],
)

# This is a dummy rule used as a @angular/cdk/testing/testbed dependency.
tf_ts_library(
    name = "expect_angular_cdk_testing_testbed",
    srcs = [],
    deps = [
        "@npm//@angular/cdk",
    ],
)

# This is a dummy rule used as a @angular/core/testing dependency.
# This is not a replacement for @angular/core dependency.
tf_ts_library(
    name = "expect_angular_core_testing",
    srcs = [],
    deps = [
        "@npm//@angular/core",
    ],
)

# This is a dummy rule used as a @angular/material/autocomplete dependency.
tf_ts_library(
    name = "expect_angular_material_autocomplete",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/checkbox dependency.
tf_ts_library(
    name = "expect_angular_material_checkbox",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/checkbox/testing dependency.
tf_ts_library(
    name = "expect_angular_material_checkbox_testing",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/button dependency.
tf_ts_library(
    name = "expect_angular_material_button",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/button_toggle dependency.
tf_ts_library(
    name = "expect_angular_material_button_toggle",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/chips dependency.
tf_ts_library(
    name = "expect_angular_material_chips",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/chips/testing dependency.
tf_ts_library(
    name = "expect_angular_material_chips_testing",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/core dependency.
tf_ts_library(
    name = "expect_angular_material_core",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/dialog dependency.
tf_ts_library(
    name = "expect_angular_material_dialog",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/dialog/testing dependency.
tf_ts_library(
    name = "expect_angular_material_dialog_testing",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/expansion dependency.
tf_ts_library(
    name = "expect_angular_material_expansion",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/expansion dependency.
tf_ts_library(
    name = "expect_angular_material_form_field",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/icon dependency.
tf_ts_library(
    name = "expect_angular_material_icon",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/icon/testing dependency.
tf_ts_library(
    name = "expect_angular_material_icon_testing",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/input dependency.
tf_ts_library(
    name = "expect_angular_material_input",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/menu dependency.
tf_ts_library(
    name = "expect_angular_material_menu",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/menu/testing dependency.
tf_ts_library(
    name = "expect_angular_material_menu_testing",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/paginator dependency.
tf_ts_library(
    name = "expect_angular_material_paginator",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/progress_spinner dependency.
tf_ts_library(
    name = "expect_angular_material_progress_spinner",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/select dependency.
tf_ts_library(
    name = "expect_angular_material_select",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/select/testing dependency.
tf_ts_library(
    name = "expect_angular_material_select_testing",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/slide_toggle dependency.
tf_ts_library(
    name = "expect_angular_material_slide_toggle",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/legacy-slider dependency.
tf_ts_library(
    name = "expect_angular_legacy_material_slider",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/slider dependency.
tf_ts_library(
    name = "expect_angular_material_slider",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/snackbar dependency.
tf_ts_library(
    name = "expect_angular_material_snackbar",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/sort dependency.
tf_ts_library(
    name = "expect_angular_material_sort",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/table dependency.
tf_ts_library(
    name = "expect_angular_material_table",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/tabs dependency.
tf_ts_library(
    name = "expect_angular_material_tabs",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/toolbar dependency.
tf_ts_library(
    name = "expect_angular_material_toolbar",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/tooltip dependency.
tf_ts_library(
    name = "expect_angular_material_tooltip",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/platform-browser/animations dependency.
# This is not a replacement for @angular/platform-browser dependency.
tf_ts_library(
    name = "expect_angular_platform_browser_animations",
    srcs = [],
    deps = ["@npm//@angular/platform-browser"],
)

# This is a dummy rule used as a @angular/platform-browser-dynamic/testing dependency.
# This is not a replacement for @angular/platform-browser-dynamic dependency.
tf_ts_library(
    name = "expect_angular_platform_browser_dynamic_testing",
    srcs = [],
    deps = ["@npm//@angular/platform-browser-dynamic"],
)

# This is a dummy rule used as a @angular/cdk/drag_drop dependency.
tf_ts_library(
    name = "expect_angular_cdk_drag_drop",
    srcs = [],
    deps = [
        "@npm//@angular/cdk",
    ],
)

# This is a dummy rule used as a @angular/cdk/overlay dependency.
tf_ts_library(
    name = "expect_angular_cdk_overlay",
    srcs = [],
    deps = [
        "@npm//@angular/cdk",
    ],
)

# This is a dummy rule used as a @angular/cdk/portal dependency.
tf_ts_library(
    name = "expect_angular_cdk_portal",
    srcs = [],
    deps = [
        "@npm//@angular/cdk",
    ],
)

# This is a dummy rule used as a @angular/cdk/scrolling dependency.
tf_ts_library(
    name = "expect_angular_cdk_scrolling",
    srcs = [],
    deps = [
        "@npm//@angular/cdk",
    ],
)

# This is a dummy rule used as a @ngrx/store/testing dependency.
# This is not a replacement for @ngrx/store dependency.
tf_ts_library(
    name = "expect_ngrx_store_testing",
    testonly = True,
    srcs = [],
    deps = [
        "@npm//@ngrx/store",
    ],
)
