load("//tensorboard/defs:defs.bzl", "tf_ts_library")

package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

# This is a dummy rule used as a @angular/common/http dependency.
# This is not a replacement for @angular/common dependency.
tf_ts_library(
    name = "expect_angular_common_http",
    srcs = [],
    visibility = [
        "//tensorboard/webapp/webapp_data_source:__subpackages__",
    ],
    deps = [
        "@npm//@angular/common",
    ],
)

# This is a dummy rule used as a @angular/common/testing dependency.
# This is not a replacement for @angular/common dependency.
tf_ts_library(
    name = "expect_angular_common_http_testing",
    srcs = [],
    visibility = [
        "//tensorboard/webapp/webapp_data_source:__subpackages__",
    ],
    deps = [
        "@npm//@angular/common",
    ],
)

# This is a dummy rule used as a @angular/core/testing dependency.
# This is not a replacement for @angular/core dependency.
tf_ts_library(
    name = "expect_angular_core_testing",
    srcs = [],
    deps = [
        "@npm//@angular/core",
    ],
)

# This is a dummy rule used as a @angular/material/tabs dependency.
tf_ts_library(
    name = "expect_angular_material_tabs",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/checkbox dependency.
tf_ts_library(
    name = "expect_angular_material_checkbox",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/button dependency.
tf_ts_library(
    name = "expect_angular_material_button",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/dialog dependency.
tf_ts_library(
    name = "expect_angular_material_dialog",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/slider dependency.
tf_ts_library(
    name = "expect_angular_material_slider",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/slide-toggle dependency.
tf_ts_library(
    name = "expect_angular_material_slide_toggle",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/toolbar dependency.
tf_ts_library(
    name = "expect_angular_material_toolbar",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/select dependency.
tf_ts_library(
    name = "expect_angular_material_select",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/icon dependency.
tf_ts_library(
    name = "expect_angular_material_icon",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/input dependency.
tf_ts_library(
    name = "expect_angular_material_input",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/platform-browser/animations dependency.
# This is not a replacement for @angular/platform-browser dependency.
tf_ts_library(
    name = "expect_angular_platform_browser_animations",
    srcs = [],
)

# This is a dummy rule used as a @angular/platform-browser-dynamic/testing dependency.
# This is not a replacement for @angular/platform-browser-dynamic dependency.
tf_ts_library(
    name = "expect_angular_platform_browser_dynamic_testing",
    srcs = [],
    deps = ["@npm//@angular/platform-browser-dynamic"],
)

# This is a dummy rule used as a @angular/cdk/overlay dependency.
tf_ts_library(
    name = "expect_angular_cdk_overlay",
    srcs = [],
    deps = [
        "@npm//@angular/cdk",
    ],
)

# This is a dummy rule used as a @angular/cdk/scrolling dependency.
tf_ts_library(
    name = "expect_angular_cdk_scrolling",
    srcs = [],
    deps = [
        "@npm//@angular/cdk",
    ],
)

# This is a dummy rule used as a @ngrx/store/testing dependency.
# This is not a replacement for @ngrx/store dependency.
tf_ts_library(
    name = "expect_ngrx_store_testing",
    testonly = True,
    srcs = [],
    deps = [
        "@npm//@ngrx/store",
    ],
)
