/* Copyright 2015 The TensorFlow Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the 'License');
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an 'AS IS' BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/
export function queryEncoder(params?: any): string {
  // It's important that the keys be sorted, so we always grab the right file
  // if we are talking to the backend generated by serialze_tensorboard.py
  if (params == null) {
    return '';
  }
  const components = _.keys(params)
                       .sort()
                       .filter((k) => params[k] !== undefined)
                       .map((k) => k + '=' + encodeURIComponent(params[k]));
  const result = components.length ? '?' + components.join('&') : '';
  // Replace parens for consistency with urllib.urlencode
  return result.replace(/\(/g, '%28').replace(/\)/g, '%29');
}
