load("//tensorboard/defs:defs.bzl", "tf_ts_library")

package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])

tf_ts_library(
    name = "tf_utils",
    srcs = [
        "utils.ts",
    ],
    strict_checks = False,
)
