load("//tensorboard/defs:defs.bzl", "tf_sass_library")

package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])

tf_sass_library(
    name = "style_lib",
    srcs = ["_lib.scss"],
    deps = ["//tensorboard/webapp:angular_material_sass_deps"],
)
