package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "test_lib",
    actual = "//tensorboard/plugins/hparams/polymer3/tf_hparams_query_pane:test_lib",
)

alias(
    name = "tf_hparams_query_pane",
    actual = "//tensorboard/plugins/hparams/polymer3/tf_hparams_query_pane:tf_hparams_query_pane",
)

alias(
    name = "schema_d_ts",
    actual = "//tensorboard/plugins/hparams/polymer3/tf_hparams_query_pane:schema_d_ts",
)
