package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_scalar_dashboard",
    actual = "//tensorboard/plugins/scalar/polymer3/tf_scalar_dashboard:tf_scalar_dashboard",
)

alias(
    name = "tf_scalar_card",
    actual = "//tensorboard/plugins/scalar/polymer3/tf_scalar_dashboard:tf_scalar_card",
)
