# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorboard/proto/tensor_description.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tensorboard.proto import types_pb2 as tensorboard_dot_proto_dot_types__pb2
from tensorboard.proto import tensor_shape_pb2 as tensorboard_dot_proto_dot_tensor__shape__pb2
from tensorboard.proto import allocation_description_pb2 as tensorboard_dot_proto_dot_allocation__description__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tensorboard/proto/tensor_description.proto',
  package='tensorboard',
  syntax='proto3',
  serialized_pb=_b('\n*tensorboard/proto/tensor_description.proto\x12\x0btensorboard\x1a\x1dtensorboard/proto/types.proto\x1a$tensorboard/proto/tensor_shape.proto\x1a.tensorboard/proto/allocation_description.proto\"\xab\x01\n\x11TensorDescription\x12$\n\x05\x64type\x18\x01 \x01(\x0e\x32\x15.tensorboard.DataType\x12,\n\x05shape\x18\x02 \x01(\x0b\x32\x1d.tensorboard.TensorShapeProto\x12\x42\n\x16\x61llocation_description\x18\x04 \x01(\x0b\x32\".tensorboard.AllocationDescriptionBw\n\x18org.tensorflow.frameworkB\x17TensorDescriptionProtosP\x01Z=github.com/tensorflow/tensorflow/tensorflow/go/core/framework\xf8\x01\x01\x62\x06proto3')
  ,
  dependencies=[tensorboard_dot_proto_dot_types__pb2.DESCRIPTOR,tensorboard_dot_proto_dot_tensor__shape__pb2.DESCRIPTOR,tensorboard_dot_proto_dot_allocation__description__pb2.DESCRIPTOR,])




_TENSORDESCRIPTION = _descriptor.Descriptor(
  name='TensorDescription',
  full_name='tensorboard.TensorDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dtype', full_name='tensorboard.TensorDescription.dtype', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='tensorboard.TensorDescription.shape', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='allocation_description', full_name='tensorboard.TensorDescription.allocation_description', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=348,
)

_TENSORDESCRIPTION.fields_by_name['dtype'].enum_type = tensorboard_dot_proto_dot_types__pb2._DATATYPE
_TENSORDESCRIPTION.fields_by_name['shape'].message_type = tensorboard_dot_proto_dot_tensor__shape__pb2._TENSORSHAPEPROTO
_TENSORDESCRIPTION.fields_by_name['allocation_description'].message_type = tensorboard_dot_proto_dot_allocation__description__pb2._ALLOCATIONDESCRIPTION
DESCRIPTOR.message_types_by_name['TensorDescription'] = _TENSORDESCRIPTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TensorDescription = _reflection.GeneratedProtocolMessageType('TensorDescription', (_message.Message,), dict(
  DESCRIPTOR = _TENSORDESCRIPTION,
  __module__ = 'tensorboard.proto.tensor_description_pb2'
  # @@protoc_insertion_point(class_scope:tensorboard.TensorDescription)
  ))
_sym_db.RegisterMessage(TensorDescription)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030org.tensorflow.frameworkB\027TensorDescriptionProtosP\001Z=github.com/tensorflow/tensorflow/tensorflow/go/core/framework\370\001\001'))
# @@protoc_insertion_point(module_scope)
