package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_markdown_view",
    actual = "//tensorboard/components_polymer3/tf_markdown_view:tf_markdown_view",
)
