package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "test_lib",
    actual = "//tensorboard/plugins/hparams/polymer3/tf_hparams_parallel_coords_plot:test_lib",
)

alias(
    name = "tf_hparams_parallel_coords_plot",
    actual = "//tensorboard/plugins/hparams/polymer3/tf_hparams_parallel_coords_plot:tf_hparams_parallel_coords_plot",
)
