package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "vz_bar_chart",
    actual = "//tensorboard/components_polymer3/vz_bar_chart:vz_bar_chart",
)
