# Description:
# Experimental framework for generic TensorBoard data providers.

package(default_visibility = ["//tensorboard:internal"])

py_library(
    name = "provider",
    srcs = ["provider.py"],
    srcs_version = "PY2AND3",
    deps = [
        "@org_pythonhosted_six",
    ],
)
