package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_color_scale",
    actual = "//tensorboard/components_polymer3/tf_color_scale:tf_color_scale",
)
