package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "demo",
    actual = "//tensorboard/plugins/distribution/polymer3/vz_distribution_chart:demo",
)

alias(
    name = "vz_distribution_chart",
    actual = "//tensorboard/plugins/distribution/polymer3/vz_distribution_chart:vz_distribution_chart",
)
