package(default_visibility = ["//tensorboard:internal"])

load("//tensorboard/defs:web.bzl", "ts_web_library")

licenses(["notice"])  # Apache 2.0

ts_web_library(
    name = "input_pipeline_analyzer",
    srcs = ["input-pipeline-analyzer.html"],
    path = "/tf-input-pipeline",
    visibility = ["//visibility:public"],
)
