package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_storage",
    actual = "//tensorboard/components_polymer3/tf_storage:tf_storage",
)
