package(
    default_testonly = True,
    default_visibility = ["//tensorboard:internal"],
)

# load("//tensorboard/defs:mocha_test.bzl", "mocha_test")

licenses(["notice"])  # Apache 2.0

# TODO(@dandelionmane): Enable this once `mocha_test` is implemented.
#mocha_test(
#    name = "test",
#    srcs = [
#        "tests.html",
#        "paginatedViewTests.html",
#        "paginatedViewTests.ts",
#    ],
#    test_file = "tests.html",
#    path = "/tf-paginated-view/test",
#    deps = [
#        "//tensorboard/components/tf_paginated_view",
#        "//tensorboard/components/tf_imports:lodash",
#        "//tensorboard/components/tf_imports:polymer",
#        "//tensorboard/components/tf_imports:webcomponentsjs",
#    ],
#)
