package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_hparams_scatter_plot_matrix_plot",
    actual = "//tensorboard/plugins/hparams/polymer3/tf_hparams_scatter_plot_matrix_plot:tf_hparams_scatter_plot_matrix_plot",
)
