load("//tensorboard/defs:defs.bzl", "tf_ts_library")

package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

tf_ts_library(
    name = "legacy_element_mixin",
    srcs = [
        "legacy_element_mixin.ts",
    ],
    deps = [
        "@npm//@polymer/polymer",
    ],
)

tf_ts_library(
    name = "paper_inky_focus_behavior",
    srcs = [
        "paper_inky_focus_behavior.ts",
    ],
    deps = [
        "@npm//@polymer/paper-behaviors",
    ],
)

tf_ts_library(
    name = "register_style_dom_module",
    srcs = [
        "register_style_dom_module.ts",
    ],
)

tf_ts_library(
    name = "utils_mixin",
    srcs = [
        "utils_mixin.ts",
    ],
    deps = [
        "@npm//@polymer/polymer",
    ],
)
