package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_hparams_session_group_details",
    actual = "//tensorboard/plugins/hparams/polymer3/tf_hparams_session_group_details:tf_hparams_session_group_details",
)
