package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_pr_curve_dashboard",
    actual = "//tensorboard/plugins/pr_curve/polymer3/tf_pr_curve_dashboard:tf_pr_curve_dashboard",
)
