package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_debugger_dashboard",
    actual = "//tensorboard/plugins/debugger/polymer3/tf_debugger_dashboard:tf_debugger_dashboard",
)
