package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "test_lib",
    actual = "//tensorboard/plugins/hparams/polymer3/tf_hparams_scale_and_color_controls:test_lib",
)

alias(
    name = "tf_hparams_scale_and_color_controls",
    actual = "//tensorboard/plugins/hparams/polymer3/tf_hparams_scale_and_color_controls:tf_hparams_scale_and_color_controls",
)
