licenses(["notice"])  # Apache 2.0

# The group of packages that are allowed to use the 'tf_hparams_main:legacy'
# webcomponent library. This allows restricting the packages that can embed
# the hparams plugin in an external web-app (outside of tensorboard).
# This is currently only used internally at google.
package_group(
    name = "whitelist",
    packages = ["//..."],
)
