package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_wbr_string",
    actual = "//tensorboard/components_polymer3/tf_wbr_string:tf_wbr_string",
)
