package(default_visibility = ["//tensorboard:internal"])

load("//tensorboard/defs:web.bzl", "tf_web_library")

licenses(["notice"])  # Apache 2.0

tf_web_library(
    name = "tf_wbr_string",
    srcs = [
        "tf-wbr-string.html",
    ],
    path = "/tf-wbr-string",
    deps = [
        "//tensorboard/components/tf_imports:polymer",
    ],
)
