package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_dashboard_common",
    actual = "//tensorboard/components_polymer3/tf_dashboard_common:tf_dashboard_common",
)
