package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "test_lib",
    actual = "//tensorboard/plugins/hparams/polymer3/tf_hparams_utils:test_lib",
)

alias(
    name = "tf_hparams_utils",
    actual = "//tensorboard/plugins/hparams/polymer3/tf_hparams_utils:tf_hparams_utils",
)
