package(default_visibility = ["//tensorboard:internal"])

load("//tensorboard/defs:defs.bzl", "tf_ts_library")

licenses(["notice"])  # Apache 2.0

# This is a dummy rule used as a @angular/common/http dependency.
# This is not a replacement for @angular/common dependency.
tf_ts_library(
    name = "expect_angular_common_http",
    srcs = [],
)

# This is a dummy rule used as a @angular/common/testing dependency.
# This is not a replacement for @angular/common dependency.
tf_ts_library(
    name = "expect_angular_common_http_testing",
    srcs = [],
)

# This is a dummy rule used as a @angular/core/testing dependency.
# This is not a replacement for @angular/core dependency.
tf_ts_library(
    name = "expect_angular_core_testing",
    srcs = [],
    deps = [
        "@npm//@angular/core",
    ],
)

# This is a dummy rule used as a @angular/material/tabs dependency.
tf_ts_library(
    name = "expect_angular_material_tabs",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/toolbar dependency.
tf_ts_library(
    name = "expect_angular_material_toolbar",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/material/select dependency.
tf_ts_library(
    name = "expect_angular_material_select",
    srcs = [],
    deps = [
        "@npm//@angular/material",
    ],
)

# This is a dummy rule used as a @angular/platform-browser/animations dependency.
# This is not a replacement for @angular/platform-browser dependency.
tf_ts_library(
    name = "expect_angular_platform_browser_animations",
    srcs = [],
)

# This is a dummy rule used as a @angular/platform-browser-dynamic/testing dependency.
# This is not a replacement for @angular/platform-browser-dynamic dependency.
tf_ts_library(
    name = "expect_angular_platform_browser_dynamic_testing",
    srcs = [],
    deps = ["@npm//@angular/platform-browser-dynamic"],
)
