package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_hparams_parallel_coords_view",
    actual = "//tensorboard/plugins/hparams/polymer3/tf_hparams_parallel_coords_view:tf_hparams_parallel_coords_view",
)
