package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_text_dashboard",
    actual = "//tensorboard/plugins/text/polymer3/tf_text_dashboard:tf_text_dashboard",
)
