package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_graph_common",
    actual = "//tensorboard/plugins/graph/polymer3/tf_graph_common:tf_graph_common",
)
