package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_hparams_sessions_pane",
    actual = "//tensorboard/plugins/hparams/polymer3/tf_hparams_sessions_pane:tf_hparams_sessions_pane",
)
