package(default_visibility = ["//tensorboard:internal"])

licenses(["notice"])  # Apache 2.0

alias(
    name = "tf_distribution_dashboard",
    actual = "//tensorboard/plugins/distribution/polymer3/tf_distribution_dashboard:tf_distribution_dashboard",
)
